import { MessageSquare, Hash, Phone, MessageCircle, ClipboardList, Gift, Cable, Server, Wallet } from "lucide-react";

export const products = [
  {
    slug: "bulk-sms",
    icon: MessageSquare,
    name: "Bulk SMS",
    tagline: "Enterprise SMS at scale",
    description: "Reach millions instantly with branded sender IDs, OTP, scheduling, and delivery analytics.",
    features: ["Sender IDs", "Bulk campaigns", "Delivery reports", "Scheduling", "OTP messaging", "Customer segmentation"],
    useCases: ["Promotions", "Notifications", "OTP verification", "Loyalty campaigns", "Customer alerts"],
    benefits: ["Instant communication", "High delivery rates", "Increased engagement", "Reliable infrastructure"],
  },
  {
    slug: "ussd",
    icon: Hash,
    name: "USSD",
    tagline: "Self-service without internet",
    description: "Interactive USSD menus for SACCOs, banking, surveys and loyalty — works on every phone.",
    features: ["Session management", "Dynamic menus", "API integrations", "Analytics", "Loyalty integrations"],
    useCases: ["SACCO services", "Banking", "Surveys", "Loyalty redemption", "Airtime purchase"],
    benefits: ["Works without internet", "Wide accessibility", "Fast engagement"],
  },
  {
    slug: "shortcodes",
    icon: Phone,
    name: "Shortcodes",
    tagline: "Memorable two-way SMS",
    description: "Dedicated and shared shortcodes with keyword routing for high-engagement campaigns.",
    features: ["Two-way SMS", "Keyword support", "API connectivity", "Campaign management"],
    useCases: ["Voting", "Promotions", "Customer care", "Lead generation"],
    benefits: ["Memorable communication", "Higher response rates", "Better engagement"],
  },
  {
    slug: "whatsapp",
    icon: MessageCircle,
    name: "WhatsApp API",
    tagline: "Conversational commerce",
    description: "Official WhatsApp Business API for support, notifications and rich broadcast messaging.",
    features: ["WhatsApp API", "Chat automation", "Notifications", "Broadcast messaging", "CRM integration"],
    useCases: ["Customer care", "Notifications", "Marketing campaigns", "Order updates"],
    benefits: ["High open rates", "Personalized communication", "Faster support"],
  },
  {
    slug: "surveys",
    icon: ClipboardList,
    name: "Surveys & Feedback",
    tagline: "Listen to your customers",
    description: "Build SMS, USSD and WhatsApp surveys with analytics dashboards and rewards.",
    features: ["Survey builder", "SMS surveys", "WhatsApp surveys", "Analytics dashboards", "Rewards engine"],
    useCases: ["Customer feedback", "Research", "Polling", "Product validation"],
    benefits: ["Better insights", "Increased engagement", "Faster decision making"],
  },
  {
    slug: "loyalty",
    icon: Gift,
    name: "Loyalty & Rewards",
    tagline: "Turn customers into fans",
    description: "Points, tiers, redemption and gamified rewards integrated with your channels.",
    features: ["Points engine", "Tiered programs", "Airtime & data redemption", "M-Pesa payouts", "Campaign automation"],
    useCases: ["Retail loyalty", "Telco rewards", "Affiliate incentives"],
    benefits: ["Higher retention", "Predictable LTV", "Customer delight"],
  },
  {
    slug: "engagement-apis",
    icon: Cable,
    name: "Engagement APIs",
    tagline: "Build with one platform",
    description: "Unified APIs for messaging, OTP, voice, contacts and webhooks. Sandbox included.",
    features: ["REST + Webhooks", "SDKs", "Sandbox keys", "Rate-limited & scalable"],
    useCases: ["Mobile apps", "ERPs", "Fintech rails"],
    benefits: ["Faster time-to-market", "Single contract", "Predictable cost"],
  },
  {
    slug: "corporate-topup",
    icon: Wallet,
    name: "Corporate Topup",
    tagline: "Bulk airtime & data, instantly",
    description: "Send airtime, bundles and data to staff, agents or customers across all networks from one dashboard or API.",
    features: ["Multi-network airtime", "Data bundles", "Bulk uploads", "Scheduled disbursement", "API & webhooks", "Approval workflows"],
    useCases: ["Staff allowances", "Agent commissions", "Customer rewards", "Field team enablement", "Promotional giveaways"],
    benefits: ["Single invoice", "Real-time delivery", "Audit-ready reports", "Lower operational cost"],
  },
  {
    slug: "enterprise-messaging",
    icon: Server,
    name: "Enterprise Messaging",
    tagline: "Carrier-grade infrastructure",
    description: "Direct MNO connectivity, SLAs, dedicated routes and priority queues for regulated workloads.",
    features: ["Direct routes", "99.9% SLA", "Compliance ready", "Dedicated capacity"],
    useCases: ["Banks", "Government", "Healthcare", "Telcos"],
    benefits: ["Predictable delivery", "Audit trails", "Regulator-friendly"],
  },
] as const;

export type Product = (typeof products)[number];
export const getProduct = (slug: string) => products.find((p) => p.slug === slug);
