/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyCenterRouteImport } from './routes/privacy-center'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDevelopersDashboardRouteImport } from './routes/_authenticated/developers.dashboard'
import { Route as AuthenticatedAffiliatesDashboardRouteImport } from './routes/_authenticated/affiliates.dashboard'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminRoleRequestsRouteImport } from './routes/_authenticated/admin.role-requests'
import { Route as AuthenticatedAdminCorporateTopupRouteImport } from './routes/_authenticated/admin.corporate-topup'
import { Route as AuthenticatedAdminConsentRouteImport } from './routes/_authenticated/admin.consent'
import { Route as AuthenticatedAdminAffiliatesRouteImport } from './routes/_authenticated/admin.affiliates'
import { Route as ApiPublicRCodeRouteImport } from './routes/api/public/r.$code'

const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyCenterRoute = PrivacyCenterRouteImport.update({
  id: '/privacy-center',
  path: '/privacy-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevelopersDashboardRoute =
  AuthenticatedDevelopersDashboardRouteImport.update({
    id: '/developers/dashboard',
    path: '/developers/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAffiliatesDashboardRoute =
  AuthenticatedAffiliatesDashboardRouteImport.update({
    id: '/affiliates/dashboard',
    path: '/affiliates/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoleRequestsRoute =
  AuthenticatedAdminRoleRequestsRouteImport.update({
    id: '/admin/role-requests',
    path: '/admin/role-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCorporateTopupRoute =
  AuthenticatedAdminCorporateTopupRouteImport.update({
    id: '/admin/corporate-topup',
    path: '/admin/corporate-topup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConsentRoute =
  AuthenticatedAdminConsentRouteImport.update({
    id: '/admin/consent',
    path: '/admin/consent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAffiliatesRoute =
  AuthenticatedAdminAffiliatesRouteImport.update({
    id: '/admin/affiliates',
    path: '/admin/affiliates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicRCodeRoute = ApiPublicRCodeRouteImport.update({
  id: '/api/public/r/$code',
  path: '/api/public/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/privacy-center': typeof PrivacyCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/consent': typeof AuthenticatedAdminConsentRoute
  '/admin/corporate-topup': typeof AuthenticatedAdminCorporateTopupRoute
  '/admin/role-requests': typeof AuthenticatedAdminRoleRequestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/affiliates/dashboard': typeof AuthenticatedAffiliatesDashboardRoute
  '/developers/dashboard': typeof AuthenticatedDevelopersDashboardRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/privacy-center': typeof PrivacyCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions': typeof SolutionsIndexRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/consent': typeof AuthenticatedAdminConsentRoute
  '/admin/corporate-topup': typeof AuthenticatedAdminCorporateTopupRoute
  '/admin/role-requests': typeof AuthenticatedAdminRoleRequestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/affiliates/dashboard': typeof AuthenticatedAffiliatesDashboardRoute
  '/developers/dashboard': typeof AuthenticatedDevelopersDashboardRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/privacy-center': typeof PrivacyCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-role': typeof SelectRoleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/_authenticated/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/_authenticated/admin/consent': typeof AuthenticatedAdminConsentRoute
  '/_authenticated/admin/corporate-topup': typeof AuthenticatedAdminCorporateTopupRoute
  '/_authenticated/admin/role-requests': typeof AuthenticatedAdminRoleRequestsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/affiliates/dashboard': typeof AuthenticatedAffiliatesDashboardRoute
  '/_authenticated/developers/dashboard': typeof AuthenticatedDevelopersDashboardRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/contact'
    | '/developers'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/privacy-center'
    | '/reset-password'
    | '/select-role'
    | '/dashboard'
    | '/auth/callback'
    | '/solutions/$slug'
    | '/solutions/'
    | '/admin/affiliates'
    | '/admin/consent'
    | '/admin/corporate-topup'
    | '/admin/role-requests'
    | '/admin/users'
    | '/affiliates/dashboard'
    | '/developers/dashboard'
    | '/api/public/r/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/contact'
    | '/developers'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/privacy-center'
    | '/reset-password'
    | '/select-role'
    | '/dashboard'
    | '/auth/callback'
    | '/solutions/$slug'
    | '/solutions'
    | '/admin/affiliates'
    | '/admin/consent'
    | '/admin/corporate-topup'
    | '/admin/role-requests'
    | '/admin/users'
    | '/affiliates/dashboard'
    | '/developers/dashboard'
    | '/api/public/r/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/contact'
    | '/developers'
    | '/forgot-password'
    | '/industries'
    | '/login'
    | '/privacy-center'
    | '/reset-password'
    | '/select-role'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/solutions/$slug'
    | '/solutions/'
    | '/_authenticated/admin/affiliates'
    | '/_authenticated/admin/consent'
    | '/_authenticated/admin/corporate-topup'
    | '/_authenticated/admin/role-requests'
    | '/_authenticated/admin/users'
    | '/_authenticated/affiliates/dashboard'
    | '/_authenticated/developers/dashboard'
    | '/api/public/r/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliatesRoute: typeof AffiliatesRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  PrivacyCenterRoute: typeof PrivacyCenterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectRoleRoute: typeof SelectRoleRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  ApiPublicRCodeRoute: typeof ApiPublicRCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-center': {
      id: '/privacy-center'
      path: '/privacy-center'
      fullPath: '/privacy-center'
      preLoaderRoute: typeof PrivacyCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developers/dashboard': {
      id: '/_authenticated/developers/dashboard'
      path: '/developers/dashboard'
      fullPath: '/developers/dashboard'
      preLoaderRoute: typeof AuthenticatedDevelopersDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliates/dashboard': {
      id: '/_authenticated/affiliates/dashboard'
      path: '/affiliates/dashboard'
      fullPath: '/affiliates/dashboard'
      preLoaderRoute: typeof AuthenticatedAffiliatesDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/role-requests': {
      id: '/_authenticated/admin/role-requests'
      path: '/admin/role-requests'
      fullPath: '/admin/role-requests'
      preLoaderRoute: typeof AuthenticatedAdminRoleRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/corporate-topup': {
      id: '/_authenticated/admin/corporate-topup'
      path: '/admin/corporate-topup'
      fullPath: '/admin/corporate-topup'
      preLoaderRoute: typeof AuthenticatedAdminCorporateTopupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/consent': {
      id: '/_authenticated/admin/consent'
      path: '/admin/consent'
      fullPath: '/admin/consent'
      preLoaderRoute: typeof AuthenticatedAdminConsentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/affiliates': {
      id: '/_authenticated/admin/affiliates'
      path: '/admin/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AuthenticatedAdminAffiliatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/r/$code': {
      id: '/api/public/r/$code'
      path: '/api/public/r/$code'
      fullPath: '/api/public/r/$code'
      preLoaderRoute: typeof ApiPublicRCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminAffiliatesRoute: typeof AuthenticatedAdminAffiliatesRoute
  AuthenticatedAdminConsentRoute: typeof AuthenticatedAdminConsentRoute
  AuthenticatedAdminCorporateTopupRoute: typeof AuthenticatedAdminCorporateTopupRoute
  AuthenticatedAdminRoleRequestsRoute: typeof AuthenticatedAdminRoleRequestsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAffiliatesDashboardRoute: typeof AuthenticatedAffiliatesDashboardRoute
  AuthenticatedDevelopersDashboardRoute: typeof AuthenticatedDevelopersDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminAffiliatesRoute: AuthenticatedAdminAffiliatesRoute,
  AuthenticatedAdminConsentRoute: AuthenticatedAdminConsentRoute,
  AuthenticatedAdminCorporateTopupRoute: AuthenticatedAdminCorporateTopupRoute,
  AuthenticatedAdminRoleRequestsRoute: AuthenticatedAdminRoleRequestsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAffiliatesDashboardRoute: AuthenticatedAffiliatesDashboardRoute,
  AuthenticatedDevelopersDashboardRoute: AuthenticatedDevelopersDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliatesRoute: AffiliatesRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  PrivacyCenterRoute: PrivacyCenterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectRoleRoute: SelectRoleRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  ApiPublicRCodeRoute: ApiPublicRCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
