/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions/$slug'
import { Route as AuthenticatedDevelopersDashboardRouteImport } from './routes/_authenticated/developers.dashboard'
import { Route as AuthenticatedAffiliatesDashboardRouteImport } from './routes/_authenticated/affiliates.dashboard'
import { Route as AuthenticatedAdminCorporateTopupRouteImport } from './routes/_authenticated/admin.corporate-topup'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDevelopersDashboardRoute =
  AuthenticatedDevelopersDashboardRouteImport.update({
    id: '/developers/dashboard',
    path: '/developers/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAffiliatesDashboardRoute =
  AuthenticatedAffiliatesDashboardRouteImport.update({
    id: '/affiliates/dashboard',
    path: '/affiliates/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCorporateTopupRoute =
  AuthenticatedAdminCorporateTopupRouteImport.update({
    id: '/admin/corporate-topup',
    path: '/admin/corporate-topup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/admin/corporate-topup': typeof AuthenticatedAdminCorporateTopupRoute
  '/affiliates/dashboard': typeof AuthenticatedAffiliatesDashboardRoute
  '/developers/dashboard': typeof AuthenticatedDevelopersDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions': typeof SolutionsIndexRoute
  '/admin/corporate-topup': typeof AuthenticatedAdminCorporateTopupRoute
  '/affiliates/dashboard': typeof AuthenticatedAffiliatesDashboardRoute
  '/developers/dashboard': typeof AuthenticatedDevelopersDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliates': typeof AffiliatesRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/_authenticated/admin/corporate-topup': typeof AuthenticatedAdminCorporateTopupRoute
  '/_authenticated/affiliates/dashboard': typeof AuthenticatedAffiliatesDashboardRoute
  '/_authenticated/developers/dashboard': typeof AuthenticatedDevelopersDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/contact'
    | '/developers'
    | '/industries'
    | '/login'
    | '/solutions/$slug'
    | '/solutions/'
    | '/admin/corporate-topup'
    | '/affiliates/dashboard'
    | '/developers/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/contact'
    | '/developers'
    | '/industries'
    | '/login'
    | '/solutions/$slug'
    | '/solutions'
    | '/admin/corporate-topup'
    | '/affiliates/dashboard'
    | '/developers/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/affiliates'
    | '/blog'
    | '/contact'
    | '/developers'
    | '/industries'
    | '/login'
    | '/solutions/$slug'
    | '/solutions/'
    | '/_authenticated/admin/corporate-topup'
    | '/_authenticated/affiliates/dashboard'
    | '/_authenticated/developers/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliatesRoute: typeof AffiliatesRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/developers/dashboard': {
      id: '/_authenticated/developers/dashboard'
      path: '/developers/dashboard'
      fullPath: '/developers/dashboard'
      preLoaderRoute: typeof AuthenticatedDevelopersDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/affiliates/dashboard': {
      id: '/_authenticated/affiliates/dashboard'
      path: '/affiliates/dashboard'
      fullPath: '/affiliates/dashboard'
      preLoaderRoute: typeof AuthenticatedAffiliatesDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/corporate-topup': {
      id: '/_authenticated/admin/corporate-topup'
      path: '/admin/corporate-topup'
      fullPath: '/admin/corporate-topup'
      preLoaderRoute: typeof AuthenticatedAdminCorporateTopupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminCorporateTopupRoute: typeof AuthenticatedAdminCorporateTopupRoute
  AuthenticatedAffiliatesDashboardRoute: typeof AuthenticatedAffiliatesDashboardRoute
  AuthenticatedDevelopersDashboardRoute: typeof AuthenticatedDevelopersDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminCorporateTopupRoute: AuthenticatedAdminCorporateTopupRoute,
  AuthenticatedAffiliatesDashboardRoute: AuthenticatedAffiliatesDashboardRoute,
  AuthenticatedDevelopersDashboardRoute: AuthenticatedDevelopersDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliatesRoute: AffiliatesRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
